image: maven:latest

variables:
  GIT_SSL_NO_VERIFY: "true"

stages:
  - build


build:
  stage: build
  only:
    - master
  tags:
    - maven
    - java
    - ubuntu

  script:
    - cp -r /var/tmp/tokens .
    - mvn clean install
    - export WEBSITE_URL="https://sats.questnr.com/"
    - export DATASOURCE_URL="jdbc:postgresql://database-1.cnuafajg7tg4.ap-south-1.rds.amazonaws.com:5432/psqlquestnr"
    - export DATASOURCE_USERNAME="psqlquestnr"
    - export DATASOURCE_PASSWORD="WpFZYf0w1Yhxn3wt3KOF"
    - export WEBSITE_API_URL="https://sats.questnr.com/api/v1"
    - export FACEBOOK_REDIRECTION_URL="https://sats.questnr.com/facebook-redirect"
    - export GOOGLE_REDIRECTION_URL="https://sats.questnr.com/google-redirect"
    - export AMAZON_S3_ENDPOINT_URL="https://s3.us-east-2.amazonaws.com"
    - export AMAZON_S3_ACCESS_KEY="AKIAQFONFFIYAZBD7B54"
    - export AMAZON_S3_SECRET_KEY="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"
    - export AMAZON_S3_BUCKET_NAME="questnr-user-files"
    - export SSL_ENABLED=false
    - export SHOW_HIBERNATE_LOGS=false
    - export ALLOW_TRENDING_SERVICES=true
    - pkill java || true
    - screen -d -m bash -c "java -jar target/web-1.0-SNAPSHOT.jar > /var/tmp/server.log 2>&1"
