image: maven:latest

variables:
  GIT_SSL_NO_VERIFY: "true"

stages:
  - build


build:
  stage: build
  only:
    - questnr

  script:
    - cp -r /var/tmp/tokens .
    - mvn clean install
    - export  WEBSITE_URL="https://questnr.com"
    - export DATASOURCE_URL="postgresql://questprodbd.cnuafajg7tg4.ap-south-1.rds.amazonaws.com/questprodb"
    - export DATASOURCE_USERNAME="questprodb"
    - export DATASOURCE_PASSWORD="yDYITyOHHfpvPvbOyGj1"
    - export  WEBSITE_API_URL="https://questnr.com/api/v1"
    - pkill java || true
    - screen -d -m bash -c "java -jar -Dapple.awt.UIElement="true" target/myproject-1.0-SNAPSHOT.jar > /var/tmp/server.log 2>&1"
