image: maven:latest

variables:
  GIT_SSL_NO_VERIFY: "true"

stages:
  - build


build:
  stage: build
  only:
    - master

  script:
    - cp -r /var/tmp/tokens .
    - mvn clean install
    - export WEBSITE_URL="https://sats.questnr.com/"
    - export DATASOURCE_URL="jdbc:postgresql://questprodbd.cnuafajg7tg4.ap-south-1.rds.amazonaws.com:5432/questprodb"
    - export DATASOURCE_USERNAME="questpro"
    - export DATASOURCE_PASSWORD="yDYITyOHHfpvPvbOyGj1"
    - export WEBSITE_API_URL="https://sats.questnr.com/api/v1"
    - export FACEBOOK_REDIRECTION_URL="https://sats.questnr.com/facebook-redirect"
    - export GOOGLE_REDIRECTION_URL="https://sats.questnr.com/google-redirect"
    - export SSL_ENABLED=false
    - export SHOW_HIBERNATE_LOGS=false
    - pkill java || true
    - screen -d -m bash -c "java -jar target/web-1.0-SNAPSHOT.jar > /var/tmp/server.log 2>&1"
